name: pydepsi

channels:
  - conda-forge

dependencies:
  - python=3.12
  - dask[complete] 
  - dask-jobqueue
  - jupyterlab
  - dask-labextension
  - matplotlib
  - pytest
  - pytest-cov
  - mkdocs
  - pip
  - pip:
    - sarxarray
    - stmtools
    - dcachefs
